const data = {
  products: [{
    "petClass": "Cat",
    "name": "WholeHearted Grain",
    "description": "WholeHearted Grain Free All Life Stages Beef & Pea Formula Dry Dog Food, 25 lbs.",
    "category": "Food",
    "image": "/uploads/img-01.jpg",
    "price": 34.99,
    "brand": "WholeHearted",
    "rating": 4.75,
    "numReviews": 1676,
    "countInStock": 10
  },
  {
    "petClass": "Dog",
    "name": "Greenies Blueberry Flavor",
    "description": "Greenies Blueberry Flavor Regular Size Dog Dental Chews, 12 oz.",
    "category": "Food",
    "image": "/uploads/img-02.jpg",
    "price": 18.98,
    "brand": "Greenies",
    "rating": 5,
    "numReviews": 450,
    "countInStock": 13
  },
  {
    "petClass": "Fish",
    "name": "Blue Buffalo Life Protection",
    "description": "Blue Buffalo Life Protection Formula Natural Senior Chicken and Brown Rice Dry Dog Food, 30 lbs.",
    "category": "Food",
    "image": "/uploads/img-03.jpg",
    "price": 69.98,
    "brand": "Blue Buffalo",
    "rating": 4.25,
    "numReviews": 430,
    "countInStock": 50
  },
  {
    "petClass": "Dog",
    "name": "Blue Buffalo Wilderness",
    "description": "Blue Buffalo Wilderness Natural Senior High Protein Grain Free Chicken Dry Dog Food, 24 lbs",
    "category": "Food",
    "image": "/uploads/img-04.jpg",
    "price": 43.58,
    "brand": "Blue Buffalo",
    "rating": 3.25,
    "numReviews": 125,
    "countInStock": 110
  },
  {
    "petClass": "Cat",
    "name": "KONG Wubba Weave",
    "description": "KONG Wubba Weave Dog Toy, Small",
    "category": "Toy",
    "image": "/uploads/img-05.jpg",
    "price": 8.55,
    "brand": "Kong",
    "rating": 3.75,
    "numReviews": 43,
    "countInStock": 234
  },
  {
    "petClass": "Cat",
    "name": "KONG Wubba Finz",
    "description": "KONG Wubba Finz Blue Toy for Dog, Small",
    "category": "Toy",
    "image": "/uploads/img-06.jpg",
    "price": 6.99,
    "brand": "Kong",
    "rating": 4.5,
    "numReviews": 22,
    "countInStock": 71
  },
  {
    "petClass": "Reptile",
    "name": "KONG SoftSeas Octopus",
    "description": "KONG SoftSeas Octopus Dog Toy, Small",
    "category": "Toy",
    "image": "/uploads/img-07.jpg",
    "price": 8.49,
    "brand": "Kong",
    "rating": 4.0,
    "numReviews": 60,
    "countInStock": 97
  },
  {
    "petClass": "Cat",
    "name": "KONG SoftSeas Turtle",
    "description": "KONG SoftSeas Turtle Dog Toy, Small",
    "category": "Toy",
    "image": "/uploads/img-08.jpg",
    "price": 3.25,
    "brand": "Kong",
    "rating": 2,
    "numReviews": 4,
    "countInStock": 85
  },
  {
    "petClass": "Cat",
    "name": "Wellness Natural Grain",
    "description": "Wellness Natural Grain Free Lamb & Salmon Recipe Soft Puppy Bites Dog Treats, 3 oz",
    "category": "Food",
    "image": "/uploads/img-09.jpg",
    "price": 4.29,
    "brand": "Wellness",
    "rating": 3.5,
    "numReviews": 283,
    "countInStock": 49
  },
  {
    "petClass": "Reptile",
    "name": "Nylabone Blue Bone",
    "description": "Nylabone Blue Bone Chicken Puppy Chew, X-Small",
    "category": "Toy",
    "image": "/uploads/img-10.jpg",
    "price": 1.99,
    "brand": "Wellness",
    "rating": 4.5,
    "numReviews": 83,
    "countInStock": 18
  },
  {
    "petClass": "Dog",
    "name": "Perfect Weight Small Bites",
    "description": "Hill's® Science Diet® Adult Perfect Weight Small Bites Dog Food",
    "category": "Food",
    "image": "/uploads/img-11.jpeg",
    "price": 23.99,
    "brand": "Hill's® Science",
    "rating": 4.3,
    "numReviews": 12,
    "countInStock": 0
  },
  {
    "petClass": "Dog",
    "name": "Perfect Weight Large Bites",
    "description": "Hill's® Science Diet® Adult Perfect Weight Large Dog Food",
    "category": "Food",
    "image": "/uploads/img-12.jpeg",
    "price": 73.99,
    "brand": "Hill's® Science",
    "rating": 4.3,
    "numReviews": 3,
    "countInStock": 10
  },
  {
    "petClass": "Dog",
    "name": "Sensitive Stomach Breed Bites",
    "description": "Hill's® Science Diet® Adult Sensitive Stomach & Skin Large Breed Dog Food",
    "category": "Food",
    "image": "/uploads/img-12.jpeg",
    "price": 79.99,
    "brand": "Hill's® Science",
    "rating": 4.9,
    "numReviews": 23,
    "countInStock": 8
  },
  {
    "petClass": "Dog",
    "name": "Sensitive Stomach Breed Bites",
    "description": "Hill's® Science Diet® Adult Sensitive Stomach & Skin Large Breed Dog Food",
    "category": "Food",
    "image": "/uploads/img-13.jpeg",
    "price": 79.99,
    "brand": "Hill's® Science",
    "rating": 4.9,
    "numReviews": 23,
    "countInStock": 8
  },
  {
    "petClass": "Dog",
    "name": "Sensitive & Small Breed Bites",
    "description": "Hill's® Science Diet® Adult Sensitive Stomach & Skin Large Breed Dog Food",
    "category": "Food",
    "image": "/uploads/img-14.jpeg",
    "price": 22.99,
    "brand": "Hill's® Science",
    "rating": 4.7,
    "numReviews": 23,
    "countInStock": 8
  },
  {
    "petClass": "Dog",
    "name": "Chicken & Barley",
    "description": "Hill's® Science Diet® Light Adult Dog Food - Chicken & Barley",
    "category": "Food",
    "image": "/uploads/img-15.jpeg",
    "price": 50.99,
    "brand": "Hill's® Science",
    "rating": 4.2,
    "numReviews": 73,
    "countInStock": 8
  },
  {
    "petClass": "Dog",
    "name": "Chicken Meal & Barley",
    "description": "Hill's® Science Diet® Light Adult Dog Food - Chicken Meal & Barley",
    "category": "Food",
    "image": "/uploads/img-16.jpeg",
    "price": 31.99,
    "brand": "Hill's® Science",
    "rating": 4.1,
    "numReviews": 76,
    "countInStock": 8
  },
  {
    "petClass": "Dog",
    "name": "Chicken Meal & Barley",
    "description": "Hill's® Science Diet® Large Breed Adult Dog Food - Chicken & Barley",
    "category": "Food",
    "image": "/uploads/img-17.jpeg",
    "price": 71.99,
    "brand": "Hill's® Science",
    "rating": 4.8,
    "numReviews": 72,
    "countInStock": 8
  },
  {
    "petClass": "Fish",
    "name": "Marina® Buffet Fish Food",
    "description": "Marina® Betta Buffet Blocks Vacation Fish Food",
    "category": "Food",
    "image": "/uploads/img-18.jpeg",
    "price": 3.99,
    "brand": "Marina®",
    "rating": 4.8,
    "numReviews": 72,
    "countInStock": 8
  },
  {
    "petClass": "Bird",
    "name": "Oven Baked Bites",
    "description": "All Living Things® Oven Baked Bites Conure & Lovebird Diet",
    "category": "Food",
    "image": "/uploads/img-19.jpeg",
    "price": 13.94,
    "brand": "Things®",
    "rating": 4.2,
    "numReviews": 22,
    "countInStock": 8
  },
  {
    "petClass": "Bird",
    "name": "Pasta Blend",
    "description": "ZuPreem® PastaBlend Parrots & Conures Pet Bird Food",
    "category": "Food",
    "image": "/uploads/img-20.jpeg",
    "price": 27.49,
    "brand": "ZuPreem®",
    "rating": 4.1,
    "numReviews": 12,
    "countInStock": 8
  },
  {
    "petClass": "Bird",
    "name": "Veggie Blend",
    "description": "ZuPreem® VeggieBlend Flavor with Natural Flavors Medium Pet Bird Food",
    "category": "Food",
    "image": "/uploads/img-21.jpeg",
    "price": 15.99,
    "brand": "ZuPreem®",
    "rating": 4.7,
    "numReviews": 112,
    "countInStock": 8
  },
  {
    "petClass": "Bird",
    "name": "Nut Blend",
    "description": "ZuPreem® NutBlend Flavour with Natural Nut Flavours Medium Pet Bird Food",
    "category": "Food",
    "image": "/uploads/img-22.jpeg",
    "price": 15.29,
    "brand": "ZuPreem®",
    "rating": 4.4,
    "numReviews": 12,
    "countInStock": 8
  },
  {
    "petClass": "Dog",
    "name": "Merrick® Texas Beef",
    "description": "Merrick® Real Texas Beef Adult Dog Food - Natural, Grain Free",
    "category": "Food",
    "image": "/uploads/img-23.jpeg",
    "price": 39.99,
    "brand": "Merrick®",
    "rating": 4.3,
    "numReviews": 28,
    "countInStock": 8
  },
  {
    "petClass": "Dog",
    "name": "Chicken & Brown Rice",
    "description": "Authority® Advanced Wellness Weight Loss Adult Dog Food - Chicken & Brown Rice",
    "category": "Food",
    "image": "/uploads/img-24.jpeg",
    "price": 51.99,
    "brand": "Authority®",
    "rating": 4.1,
    "numReviews": 22,
    "countInStock": 8
  },
  {
    "petClass": "Dog",
    "name": "Simply Nourish® Puppy Food",
    "description": "Simply Nourish® Puppy Food - Natural, Chicken & Brown Rice",
    "category": "Food",
    "image": "/uploads/img-25.jpeg",
    "price": 55.99,
    "brand": "Simply Nourish®",
    "rating": 4.8,
    "numReviews": 72,
    "countInStock": 8
  },
  {
    "petClass": "Cat",
    "name": "PureBites® Dried Turkey",
    "description": "PureBites® Freeze Dried Holiday Cat Treat - Turkey",
    "category": "Food",
    "image": "/uploads/img-26.jpeg",
    "price": 6.99,
    "brand": "PureBites®",
    "rating": 4.1,
    "numReviews": 42,
    "countInStock": 8
  }
  ]
};

export default data;