export default {
  products: [{
    "petClass": "Cat",
    "name": "WholeHearted Grain",
    "description": "WholeHearted Grain Free All Life Stages Beef & Pea Formula Dry Dog Food, 25 lbs.",
    "category": "Food",
    "image": "/uploads/img-01.jpg",
    "price": 34.99,
    "brand": "WholeHearted",
    "rating": 4.75,
    "numReviews": 1676,
    "countInStock": 10
  },
  {
    "petClass": "Dog",
    "name": "Greenies Blueberry Flavor",
    "description": "Greenies Blueberry Flavor Regular Size Dog Dental Chews, 12 oz.",
    "category": "Food",
    "image": "/uploads/img-02.jpg",
    "price": 18.98,
    "brand": "Greenies",
    "rating": 5,
    "numReviews": 450,
    "countInStock": 13
  },
  {
    "petClass": "Cat",
    "name": "Blue Buffalo Life Protection",
    "description": "Blue Buffalo Life Protection Formula Natural Senior Chicken and Brown Rice Dry Dog Food, 30 lbs.",
    "category": "Food",
    "image": "/uploads/img-03.jpg",
    "price": 69.98,
    "brand": "Blue Buffalo",
    "rating": 4.25,
    "numReviews": 430,
    "countInStock": 50
  },
  {
    "petClass": "Dog",
    "name": "Blue Buffalo Wilderness",
    "description": "Blue Buffalo Wilderness Natural Senior High Protein Grain Free Chicken Dry Dog Food, 24 lbs",
    "category": "Food",
    "image": "/uploads/img-04.jpg",
    "price": 43.58,
    "brand": "Blue Buffalo",
    "rating": 3.25,
    "numReviews": 125,
    "countInStock": 110
  },
  {
    "petClass": "Cat",
    "name": "KONG Wubba Weave",
    "description": "KONG Wubba Weave Dog Toy, Small",
    "category": "Toy",
    "image": "/uploads/img-05.jpg",
    "price": 8.55,
    "brand": "Kong",
    "rating": 3.75,
    "numReviews": 43,
    "countInStock": 234
  },
  {
    "petClass": "Cat",
    "name": "KONG Wubba Finz",
    "description": "KONG Wubba Finz Blue Toy for Dog, Small",
    "category": "Toy",
    "image": "/uploads/img-06.jpg",
    "price": 6.99,
    "brand": "Kong",
    "rating": 4.5,
    "numReviews": 22,
    "countInStock": 71
  },
  {
    "petClass": "Cat",
    "name": "KONG SoftSeas Octopus",
    "description": "KONG SoftSeas Octopus Dog Toy, Small",
    "category": "Toy",
    "image": "/uploads/img-07.jpg",
    "price": 8.49,
    "brand": "Kong",
    "rating": 4.0,
    "numReviews": 60,
    "countInStock": 97
  },
  {
    "petClass": "Cat",
    "name": "KONG SoftSeas Turtle",
    "description": "KONG SoftSeas Turtle Dog Toy, Small",
    "category": "Toy",
    "image": "/uploads/img-08.jpg",
    "price": 3.25,
    "brand": "Kong",
    "rating": 2,
    "numReviews": 4,
    "countInStock": 85
  },
  {
    "petClass": "Cat",
    "name": "Wellness Natural Grain",
    "description": "Wellness Natural Grain Free Lamb & Salmon Recipe Soft Puppy Bites Dog Treats, 3 oz",
    "category": "Food",
    "image": "/uploads/img-09.jpg",
    "price": 4.29,
    "brand": "Wellness",
    "rating": 3.5,
    "numReviews": 283,
    "countInStock": 49
  },
  {
    "petClass": "Dog",
    "name": "Nylabone Blue Bone",
    "description": "Nylabone Blue Bone Chicken Puppy Chew, X-Small",
    "category": "Toy",
    "image": "/uploads/img-10.jpg",
    "price": 1.99,
    "brand": "Wellness",
    "rating": 4.5,
    "numReviews": 83,
    "countInStock": 18
  },
  {
    "petClass": "Dog",
    "name": "Nylabone Blue Bone",
    "description": "Nylabone Blue Bone Chicken Puppy Chew, X-Small",
    "category": "Toy",
    "image": "/uploads/img-10.jpg",
    "price": 1.99,
    "brand": "Wellness",
    "rating": 4.5,
    "numReviews": 83,
    "countInStock": 18
  },
  {
    "petClass": "Dog",
    "name": "Nylabone Blue Bone",
    "description": "Nylabone Blue Bone Chicken Puppy Chew, X-Small",
    "category": "Toy",
    "image": "/uploads/img-10.jpg",
    "price": 1.99,
    "brand": "Wellness",
    "rating": 4.5,
    "numReviews": 83,
    "countInStock": 18
  },
  {
    "petClass": "Dog",
    "name": "Nylabone Blue Bone 01",
    "description": "Nylabone Blue Bone 01 Chicken Puppy Chew, X-Small",
    "category": "Toy",
    "image": "/uploads/img-10.jpg",
    "price": 1.99,
    "brand": "Wellness",
    "rating": 3.9,
    "numReviews": 87,
    "countInStock": 18
  },
  {
    "petClass": "Dog",
    "name": "Nylabone Blue Bone 02",
    "description": "Nylabone Blue Bone 02 Chicken Puppy Chew, X-Small",
    "category": "Toy",
    "image": "/uploads/img-10.jpg",
    "price": 2.99,
    "brand": "Wellness",
    "rating": 3.5,
    "numReviews": 72,
    "countInStock": 18
  },
  {
    "petClass": "Dog",
    "name": "Nylabone Blue Bone 03",
    "description": "Nylabone Blue Bone 03 Chicken Puppy Chew, X-Small",
    "category": "Toy",
    "image": "/uploads/img-10.jpg",
    "price": 3.99,
    "brand": "Wellness",
    "rating": 4.7,
    "numReviews": 12,
    "countInStock": 18
  }
  ]
}